spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.145.129:3306/passjava_chms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: abc123__
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.145.129:8848

