spring:
  profiles:
    include: common
  application:
    name: passjava-question
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 11000

feign:
  client:
    config:
      default:
        connectTimeout: 50000  # 连接超时时间，单位：毫秒
        readTimeout: 100000    # 读取超时时间，单位：毫秒