spring:
  profiles:
    include: common, jwt
  application:
    name: passjava-auth

server:
  port: 10001

feign:
  client:
    config:
      default:
        connectTimeout: 50000  # 连接超时时间，单位：毫秒
        readTimeout: 100000    # 读取超时时间，单位：毫秒

